void DrawOpenWindow(void *);
void DrawSaveWindow(void *);
void DrawSaveAsWindow(void *);
void DrawFindWindow(void *);
void DrawReplaceWindow(void *);
void SwitchTextBox(void *n);

void CloseChildWindow(void *);
void CheckChildButton(void *);
void MoveChildWindow(void *n);

void CheckEnterSubmit(void *n);
void SubmitButton(void *n);
void OpenButton(void *n);
void MsgBoxButton(void *n);
void CancelButton(void *n);
